name: Trigger auto deployment for containertest02-21

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/containertest02-21-AutoDeployTrigger-f8740d61-452b-45f7-a44a-71ee9f07957f.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERTEST0221_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERTEST0221_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERTEST0221_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERTEST0221_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERTEST0221_REGISTRY_PASSWORD }}
          containerAppName: containertest02-21
          resourceGroup: Mustaphatest
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


